spring.application.name=POS

#Hibernate (Day-1)	https://drive.google.com/drive/folders/1MHp17MKGvI9MSPHLvTGqYPJeics-CoAJ?usp=drive_link
#Hibernate (Day-2)	https://drive.google.com/drive/folders/1ITAw4mbFjj7PUwYsNkJ0eiRlGray6Mi4?usp=drive_link
#Hibernate (Day-3)	https://drive.google.com/drive/folders/12LU2m4UYhgbfxjXQBCx45w65ia8se7vJ?usp=drive_link